/**
 * Edu ID Generator Module
 * Implements architectural Gang of Four (GoF) patterns:
 * - Singleton Pattern: Ensures a single global registry / manager instance
 * - Strategy Pattern: Allows pluggable generation algorithms (e.g. mock vs crypto-secure)
 * - Factory Method Pattern: Instantiates appropriate prefixed IDs based on Firestore collection types
 */

import crypto from 'crypto';

// Strategy Interface for generating unique string values
export interface IdGenerationStrategy {
  generate(collectionName: string): string;
}

// Concrete Strategy: Produces cryptographically-secure, prefixed "edu-" unique keys
export class CryptographicEduStrategy implements IdGenerationStrategy {
  private getPrefix(collectionName: string): string {
    switch (collectionName) {
      case 'schools': return 'sch';
      case 'login_options': return 'opt';
      case 'users': return 'usr';
      case 'invitations': return 'inv';
      case 'secure_exam_links': return 'lnk';
      case 'exams': return 'exm';
      case 'questions': return 'qst';
      case 'attempts': return 'att';
      case 'microschedules': return 'schd';
      case 'error_books': return 'err';
      case 'proctoring_logs': return 'prc';
      case 'syllabus': return 'syl';
      default: return 'gen';
    }
  }

  generate(collectionName: string): string {
    const prefix = this.getPrefix(collectionName);
    
    // We try to use Node's crypto API on the server, and fall back to standard web-crypto or math-random on the client.
    let randomHex = '';
    if (typeof window === 'undefined' && crypto && crypto.randomBytes) {
      randomHex = crypto.randomBytes(8).toString('hex');
    } else {
      // Client-side secure or math-random fallback
      const array = new Uint32Array(2);
      if (typeof window !== 'undefined' && window.crypto && window.crypto.getRandomValues) {
        window.crypto.getRandomValues(array);
        randomHex = Array.from(array).map(b => b.toString(16).padStart(8, '0')).join('');
      } else {
        randomHex = Math.random().toString(16).substring(2, 10) + Math.random().toString(16).substring(2, 10);
      }
    }
    
    const timestamp = Date.now().toString(36);
    return `edu-${prefix}-${timestamp}-${randomHex.substring(0, 12)}`;
  }
}

// GoF Factory Method & Singleton Context manager
export class EduKeyFactory {
  private static instance: EduKeyFactory | null = null;
  private strategy: IdGenerationStrategy;

  // Private constructor prevents multiple instances (Singleton)
  private constructor() {
    this.strategy = new CryptographicEduStrategy();
  }

  // Retrieve the static Singleton instance
  public static getInstance(): EduKeyFactory {
    if (!EduKeyFactory.instance) {
      EduKeyFactory.instance = new EduKeyFactory();
    }
    return EduKeyFactory.instance;
  }

  // Strategy Setter allows changing ID generation logic dynamically at runtime (Strategy Pattern)
  public setStrategy(strategy: IdGenerationStrategy): void {
    this.strategy = strategy;
  }

  // Generates prefixed "edu-" autogenerated key (Factory Method Pattern)
  public generateKey(collectionName: string): string {
    return this.strategy.generate(collectionName);
  }
}
