version: '3.8'

services:
  suvenedu-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suvenedu-production-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
