import express from 'express';
import { EduKeyFactory } from '../../src/lib/idGenerator';
import { signSessionToken } from '../auth/tokens';
import { gatekeeperLookupLimiter, gatekeeperEnrollLimiter } from '../middleware/rateLimit';
import { LOAD_TEST_SECRET } from '../config';
import {
  clientDb,
  clientCollection,
  clientDoc,
  clientGetDoc,
  clientGetDocs,
  clientSetDoc,
  clientUpdateDoc,
  clientQuery,
  clientWhere,
  clientRunTransaction
} from '../firestoreClient';

const router = express.Router();

// In-Memory Store for High-Concurrency Load Tests to prevent consuming Cloud Firestore quota.
// Exported: /api/db/write's isLoadTestWrite branch reads/writes the same store.
export const mockLoadTestStore = new Map<string, any>();

// Pre-session identity verification for the invite-link student flow: resolves (or
// auto-onboards) a student by roll number + school, exactly mirroring what the client used
// to do via direct (now-unauthenticated-blocked) Firestore calls to the `users` collection.
// Runs before any session exists — same trust model as /api/gatekeeper/enroll itself, which
// is the only reason this needs to be its own public route rather than going through the
// now-authenticated /api/db/query proxy.
/**
 * @openapi
 * /api/gatekeeper/verify-identity:
 *   post:
 *     summary: Resolve (or auto-onboard) a student by roll number + school for the invite-link entry flow
 *     description: Pre-session route — runs before any session token exists, so it is intentionally public. Rate-limited (gatekeeperLookupLimiter).
 *     tags: [Gatekeeper]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [rollNumber, schoolId, username]
 *             properties:
 *               rollNumber: { type: string }
 *               schoolId: { type: string }
 *               username: { type: string }
 *     responses:
 *       200:
 *         description: Resolved (or newly auto-onboarded) student profile
 *       400:
 *         description: Missing rollNumber, schoolId, or username
 *       500:
 *         description: Server/Firestore error
 */
router.post('/api/gatekeeper/verify-identity', gatekeeperLookupLimiter, async (req, res) => {
  const { rollNumber, schoolId: finalSchoolId, username } = req.body;
  if (!rollNumber || !finalSchoolId || !username) {
    return res.status(400).json({ error: 'Missing rollNumber, schoolId, or username.' });
  }

  try {
    const usersRef = clientCollection(clientDb, 'users');
    let querySnap = await clientGetDocs(
      clientQuery(
        usersRef,
        clientWhere('schoolId', '==', finalSchoolId),
        clientWhere('rollNumber', '==', rollNumber.trim()),
        clientWhere('role', '==', 'student')
      )
    );

    if (querySnap.empty) {
      querySnap = await clientGetDocs(
        clientQuery(usersRef, clientWhere('rollNumber', '==', rollNumber.trim()), clientWhere('role', '==', 'student'))
      );
    }

    let profileData: any;

    if (!querySnap.empty) {
      const matchedDoc = querySnap.docs[0];
      const matchedStudentData = matchedDoc.data() as any;

      profileData = {
        uid: matchedDoc.id,
        id: matchedDoc.id,
        ...matchedStudentData,
        name: matchedStudentData.name || username.trim(),
        schoolId: matchedStudentData.schoolId || finalSchoolId
      };
    } else {
      // Auto-onboard student for seamless link entry
      const newStudentId = EduKeyFactory.getInstance().generateKey('users');
      profileData = {
        uid: newStudentId,
        id: newStudentId,
        name: username.trim(),
        rollNumber: rollNumber.trim(),
        schoolId: finalSchoolId,
        role: 'student',
        permissions: ['take_exams'],
        createdAt: new Date().toISOString(),
        class: 'Adaptive Grade'
      };
      await clientSetDoc(clientDoc(clientDb, 'users', newStudentId), profileData);
    }

    return res.status(200).json({ success: true, profileData });
  } catch (err: any) {
    console.error('Gatekeeper identity verification error:', err);
    return res.status(500).json({ error: err.message || String(err) });
  }
});

// Pre-session metadata lookup for the per-student invite-link flow (`/login?invite=<token>`,
// generated by SchoolStudentOnboarding.tsx). Mirrors the old client-side direct-Firestore
// version exactly, just moved server-side since `invitations`/`users` now require a session.
/**
 * @openapi
 * /api/gatekeeper/invite-metadata:
 *   post:
 *     summary: Look up invite/student/school metadata for a per-student invite link
 *     description: Pre-session route (invitations/users require a session for direct access, so this proxies the lookup). Public. Rate-limited (gatekeeperLookupLimiter).
 *     tags: [Gatekeeper]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [inviteToken]
 *             properties:
 *               inviteToken: { type: string }
 *     responses:
 *       200:
 *         description: Invite data, resolved student profile, and school (if any)
 *       400:
 *         description: Missing inviteToken
 *       404:
 *         description: Invite is invalid or expired
 *       422:
 *         description: Invite exists but is missing required schoolId
 *       500:
 *         description: Server/Firestore error
 */
router.post('/api/gatekeeper/invite-metadata', gatekeeperLookupLimiter, async (req, res) => {
  const { inviteToken } = req.body;
  if (!inviteToken) {
    return res.status(400).json({ error: 'Missing inviteToken.' });
  }

  try {
    const inviteSnap = await clientGetDoc(clientDoc(clientDb, 'invitations', inviteToken));

    if (!inviteSnap.exists()) {
      // Previously fell back to a schoolless, platform-wide roll-number search — that let
      // anyone with zero information (no valid invite needed) query any student's profile
      // by guessing a roll number, with no tenant boundary. A broken/expired link should
      // fail cleanly instead; the properly-scoped exam-entry link is unaffected.
      return res.status(404).json({ error: 'This invitation link is invalid or has expired. Please contact your school for a new link.' });
    }

    const iData = { id: inviteSnap.id, ...inviteSnap.data() } as any;
    if (!iData.schoolId) {
      // A school is required to scope this invite — silently defaulting to a placeholder
      // school here would previously have attached the student to the wrong tenant with no
      // visible error. This invite doc is malformed; fail loudly instead.
      console.error(`Invitation ${inviteToken} is missing schoolId — cannot resolve student.`);
      return res
        .status(422)
        .json({ error: 'This invitation is missing required school information. Please contact your school for a new link.' });
    }
    const resolvedStudentId = iData.studentId || `student-${inviteToken}`;

    let studentProfile: any;
    try {
      const studentSnap = await clientGetDoc(clientDoc(clientDb, 'users', resolvedStudentId));
      if (!studentSnap.exists()) {
        studentProfile = {
          uid: resolvedStudentId,
          name: iData.studentName || 'Candidate',
          rollNumber: 'ROLL-TEMP',
          schoolId: iData.schoolId,
          role: 'student',
          permissions: ['take_exams'],
          createdAt: new Date().toISOString(),
          class: 'Adaptive Grade'
        };
        await clientSetDoc(clientDoc(clientDb, 'users', resolvedStudentId), studentProfile);
      } else {
        studentProfile = { uid: studentSnap.id, ...studentSnap.data() };
      }
    } catch (studentErr) {
      console.warn('Could not retrieve/create user profile directly:', studentErr);
      studentProfile = {
        uid: resolvedStudentId,
        name: iData.studentName || 'Candidate',
        rollNumber: 'ROLL-TEMP',
        schoolId: iData.schoolId,
        role: 'student',
        permissions: ['take_exams'],
        createdAt: new Date().toISOString(),
        class: 'Adaptive Grade'
      };
    }

    let school: any = null;
    if (iData.schoolId) {
      try {
        const schoolSnap = await clientGetDoc(clientDoc(clientDb, 'schools', iData.schoolId));
        if (schoolSnap.exists()) school = { id: schoolSnap.id, ...schoolSnap.data() };
      } catch (e) {
        /* non-fatal */
      }
    }

    return res.status(200).json({ success: true, inviteData: iData, studentProfile, school });
  } catch (err: any) {
    console.error('Invitation gateway error:', err);
    return res.status(500).json({ error: err.message || String(err) });
  }
});

// Pre-session identity + target-exam resolution for the per-student invite-link flow. The
// actual attempt creation/resume is deliberately NOT done here — the client follows this
// call with /api/gatekeeper/enroll (passing this route's output plus inviteToken), reusing
// its already-correct resume/reattempt/already-completed transaction logic instead of a
// second, divergent copy of it.
/**
 * @openapi
 * /api/gatekeeper/verify-invite:
 *   post:
 *     summary: Verify a student's entered name/roll against an invite and resolve the target exam
 *     description: Pre-session route. Does not create/resume an attempt itself — the client follows this with /api/gatekeeper/enroll. Public. Rate-limited (gatekeeperLookupLimiter).
 *     tags: [Gatekeeper]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [enteredName, enteredRoll]
 *             properties:
 *               inviteToken: { type: string }
 *               enteredName: { type: string }
 *               enteredRoll: { type: string }
 *     responses:
 *       200:
 *         description: Resolved student + target exam/school info
 *       400:
 *         description: Missing name/roll number, or input failed HTML/script sanitization check
 *       404:
 *         description: Invite is invalid or expired
 *       422:
 *         description: Invite exists but is missing required schoolId
 *       500:
 *         description: Server/Firestore error
 */
router.post('/api/gatekeeper/verify-invite', gatekeeperLookupLimiter, async (req, res) => {
  const { inviteToken, enteredName, enteredRoll } = req.body;
  if (!enteredName || !enteredRoll) {
    return res.status(400).json({ error: 'Please enter both your Full Name and Register / Roll Number' });
  }

  const containsHTMLOrScripts = (val: string) => {
    const lowercase = val.toLowerCase();
    return (
      lowercase.includes('<script') ||
      lowercase.includes('javascript:') ||
      lowercase.includes('<') ||
      lowercase.includes('>') ||
      lowercase.includes('onload')
    );
  };
  const trimmedName = enteredName.trim();
  const trimmedRoll = enteredRoll.trim();
  if (containsHTMLOrScripts(trimmedName) || containsHTMLOrScripts(trimmedRoll)) {
    return res.status(400).json({ error: 'Invalid credentials provided' });
  }

  try {
    // A valid, existing invitation is required — no schoolless fallback search. That
    // fallback used to let anyone query any student's profile platform-wide by guessing a
    // roll number with zero prior information (no invite needed at all), since roll
    // numbers are only unique within a school and there was no school to scope by.
    const inviteSnap = inviteToken ? await clientGetDoc(clientDoc(clientDb, 'invitations', inviteToken)) : null;
    if (!inviteSnap || !inviteSnap.exists()) {
      return res.status(404).json({ error: 'This invitation link is invalid or has expired. Please contact your school for a new link.' });
    }
    const iData: any = { id: inviteSnap.id, ...inviteSnap.data() };
    if (!iData.schoolId) {
      // See invite-metadata's identical guard above — a missing schoolId on the invite doc
      // must fail loudly, not silently default to a placeholder school.
      console.error(`Invitation ${inviteToken} is missing schoolId — cannot resolve student.`);
      return res
        .status(422)
        .json({ error: 'This invitation is missing required school information. Please contact your school for a new link.' });
    }

    const targetExamId = iData.examId;
    const targetExamTitle = iData.examTitle || 'Institution Secure Exam';
    const targetSchoolId = iData.schoolId;

    let resolvedStudentProfile: any;
    const usersRef = clientCollection(clientDb, 'users');

    const querySnap = await clientGetDocs(
      clientQuery(usersRef, clientWhere('rollNumber', '==', trimmedRoll), clientWhere('schoolId', '==', targetSchoolId))
    );

    if (!querySnap.empty) {
      const matchProfile = querySnap.docs[0].data() as any;
      const matchId = querySnap.docs[0].id;
      resolvedStudentProfile = { uid: matchId, ...matchProfile, name: matchProfile.name || trimmedName };
      if (!matchProfile.name) {
        await clientSetDoc(clientDoc(clientDb, 'users', matchId), resolvedStudentProfile);
      }
    } else {
      const newStudentId = EduKeyFactory.getInstance().generateKey('users');
      resolvedStudentProfile = {
        uid: newStudentId,
        name: trimmedName,
        rollNumber: trimmedRoll,
        schoolId: targetSchoolId,
        role: 'student',
        permissions: ['take_exams'],
        createdAt: new Date().toISOString(),
        class: 'Adaptive Grade'
      };
      await clientSetDoc(clientDoc(clientDb, 'users', newStudentId), resolvedStudentProfile);
    }

    return res.status(200).json({
      success: true,
      matchedStudentId: resolvedStudentProfile.uid,
      matchedStudentData: resolvedStudentProfile,
      finalSchoolId: targetSchoolId,
      finalExamId: targetExamId,
      examTitle: targetExamTitle,
      isFallback: false
    });
  } catch (err: any) {
    console.error('Invite verification error:', err);
    return res.status(500).json({ error: err.message || String(err) });
  }
});

// Direct student login from the main login page (no exam link/invite involved): same
// credential shape as the link-entry flow (name + roll/register number), but scoped by
// roll number alone since there's no school context to disambiguate with. Unlike
// verify-identity/verify-invite, this never auto-onboards on a miss — a mistyped roll number
// here has no school/invite to safely attach a new account to, so it must fail cleanly
// instead of silently creating a bogus student record.
/**
 * @openapi
 * /api/gatekeeper/student-login:
 *   post:
 *     summary: Direct student login by name + roll number (no exam link/invite involved)
 *     description: Pre-session route — mints the session token itself, so it is intentionally public. DOB is optional at onboarding, so it's optional here too — checked only when both entered and present on the account; never onboards a new account on a miss. Rate-limited (gatekeeperLookupLimiter).
 *     tags: [Gatekeeper]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [name, rollNumber]
 *             properties:
 *               name: { type: string }
 *               rollNumber: { type: string }
 *               dob: { type: string, description: "Optional. Checked only if both this and the account's on-file DOB are present." }
 *     responses:
 *       200:
 *         description: Login succeeded — returns profile + session token
 *       400:
 *         description: Missing name or roll number
 *       401:
 *         description: DOB provided but doesn't match the account's on-file DOB
 *       404:
 *         description: No student account found for that roll number
 *       409:
 *         description: Roll number is ambiguous across multiple student accounts
 *       500:
 *         description: Server/Firestore error
 */
router.post('/api/gatekeeper/student-login', gatekeeperLookupLimiter, async (req, res) => {
  const { name, rollNumber, dob } = req.body;
  if (!name || !rollNumber) {
    return res.status(400).json({ error: 'Please enter both your Full Name and Register / Roll Number' });
  }

  const trimmedRoll = rollNumber.trim();
  const trimmedName = name.trim();
  const trimmedDob = typeof dob === 'string' ? dob.trim() : '';
  if (!trimmedRoll || !trimmedName) {
    return res.status(400).json({ error: 'Please enter both your Full Name and Register / Roll Number' });
  }

  try {
    const usersRef = clientCollection(clientDb, 'users');
    const querySnap = await clientGetDocs(
      clientQuery(usersRef, clientWhere('rollNumber', '==', trimmedRoll), clientWhere('role', '==', 'student'))
    );

    if (querySnap.empty) {
      return res
        .status(404)
        .json({ error: 'No student account found for that Register / Roll Number. Ask your school to onboard you first.' });
    }

    // Roll numbers are only guaranteed unique within a school. Without a school to scope by
    // here, more than one match is a genuine ambiguity — fail with a clear message rather
    // than silently guessing which student this is.
    if (querySnap.docs.length > 1) {
      return res.status(409).json({
        error: "Multiple student accounts share this Register / Roll Number. Please sign in via your school's exam link instead."
      });
    }

    const matchedDoc = querySnap.docs[0];
    const matchedData = matchedDoc.data() as any;

    // DOB is optional at onboarding, so it's optional here too: checked only when the
    // student entered one AND the account actually has one on file. Product decision,
    // accepted with known risk — roll-number-only login remains possible for accounts
    // with no DOB set, or when the DOB field is left blank at login.
    if (trimmedDob && matchedData.dob && String(matchedData.dob).trim() !== trimmedDob) {
      return res.status(401).json({ error: 'Full Name, Register / Roll Number, or Date of Birth does not match our records.' });
    }

    const profileData = {
      uid: matchedDoc.id,
      id: matchedDoc.id,
      ...matchedData,
      name: matchedData.name || trimmedName
    };

    const sessionToken = signSessionToken({
      uid: profileData.uid,
      role: 'student',
      schoolId: profileData.schoolId || null,
      email: profileData.email || null
    });

    return res.status(200).json({ success: true, profileData, sessionToken });
  } catch (err: any) {
    console.error('Gatekeeper student-login error:', err);
    return res.status(500).json({ error: err.message || String(err) });
  }
});

/**
 * @openapi
 * /api/gatekeeper/enroll:
 *   post:
 *     summary: Atomically create/resume/reattempt an exam attempt and mint the student's session
 *     description: >
 *       Pre-session route — mints the session token itself, so it is intentionally public.
 *       Runs an atomic Firestore transaction covering student onboarding, attempt
 *       creation/resume/reattempt, and exam-window expiry. Supports an internal load-test
 *       bypass gated on a server-side secret (`x-load-test-secret` header must match
 *       LOAD_TEST_SECRET, which is unset/disabled in normal deployments — fail-closed, not
 *       merely unauthenticated). Rate-limited (gatekeeperEnrollLimiter).
 *     tags: [Gatekeeper]
 *     security: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [finalSchoolId, finalExamId, rollNumber]
 *             properties:
 *               matchedStudentId: { type: string }
 *               matchedStudentData: { type: object }
 *               username: { type: string }
 *               rollNumber: { type: string }
 *               finalSchoolId: { type: string }
 *               finalExamId: { type: string }
 *               examTitle: { type: string }
 *               clientFootprint: { type: string, description: "Opaque device fingerprint used to detect session hijack across devices." }
 *               inviteToken: { type: string }
 *               inviteIsFallback: { type: boolean }
 *     responses:
 *       200:
 *         description: Attempt created/resumed/reattempted, with session token and resolved profile
 *       400:
 *         description: Missing finalSchoolId, finalExamId, or rollNumber
 *       403:
 *         description: SESSION_HIJACK_BLOCKED — device footprint mismatch against the attempt's registered device
 *       409:
 *         description: EXAM_ALREADY_COMPLETED — attempt already submitted and not eligible for reattempt
 *       410:
 *         description: EXAM_WINDOW_EXPIRED — exam's time window has passed
 *       500:
 *         description: Transaction/server error
 */
// 2. BACKEND API FOR HEAVY WRITES: THE GATEKEEPER TRANSACTION
router.post('/api/gatekeeper/enroll', gatekeeperEnrollLimiter, async (req, res) => {
  const {
    matchedStudentId,
    matchedStudentData,
    username,
    rollNumber,
    finalSchoolId,
    finalExamId,
    examTitle,
    clientFootprint,
    inviteToken,
    inviteIsFallback
  } = req.body;

  if (!finalSchoolId || !finalExamId || !rollNumber) {
    return res.status(400).json({ error: 'Missing required validation payload parameters.' });
  }

  const now = new Date();
  const resolvedStudentId = matchedStudentId || `std_${finalSchoolId}_${rollNumber.trim().replace(/\s+/g, '_').toLowerCase()}`;
  const studentDocRef = clientDoc(clientDb, 'users', resolvedStudentId);
  const attemptIdRaw = `att_${finalExamId}_${resolvedStudentId}`;
  const attemptDocRef = clientDoc(clientDb, 'attempts', attemptIdRaw);
  const examDocRef = clientDoc(clientDb, 'exams', finalExamId);

  // Gated on a server-side secret (never client-suppliable) rather than the header alone —
  // this branch mints a real, verifiable session token, so trusting a bare client-sent
  // header (or worse, guessable substrings in attacker-controlled body fields) let anyone
  // forge a valid student session for free with zero enrollment. If LOAD_TEST_SECRET isn't
  // configured, this bypass is fully disabled (fail-closed), not merely unauthenticated.
  const isLoadTestRequest =
    !!LOAD_TEST_SECRET && req.headers['x-load-test'] === 'true' && req.headers['x-load-test-secret'] === LOAD_TEST_SECRET;

  if (isLoadTestRequest) {
    const mockProfile = {
      uid: resolvedStudentId,
      name: username?.trim() || `Simulated Student ${rollNumber}`,
      rollNumber: rollNumber.trim(),
      schoolId: finalSchoolId,
      role: 'student',
      permissions: ['take_exams'],
      createdAt: now.toISOString(),
      class: 'Adaptive Cluster'
    };
    const mockAttempt = {
      examId: finalExamId,
      examTitle: examTitle || 'Stress Test Simulated Exam',
      studentId: resolvedStudentId,
      studentName: mockProfile.name,
      studentEmail: `${rollNumber.trim().toLowerCase()}@school.com`,
      schoolId: finalSchoolId,
      answers: [],
      score: 0,
      startTime: now.toISOString(),
      status: 'started',
      deviceFootprint: clientFootprint || 'StressTesterWorkerNode',
      ephemeralToken: 'MOCK_TOKEN_LOADTEST',
      timePerQuestion: {}
    };
    mockLoadTestStore.set(`users_${resolvedStudentId}`, mockProfile);
    mockLoadTestStore.set(`attempts_${attemptIdRaw}`, mockAttempt);

    // A signed JWT needs no Firestore write/lookup either way, so the load-test path now
    // gets a real session token for free — no more special-cased in-memory session map.
    const loadTestSessionToken = signSessionToken({
      uid: resolvedStudentId,
      role: 'student',
      schoolId: finalSchoolId,
      email: null
    });

    return res.status(200).json({
      success: true,
      resolvedStudentId,
      attemptIdRaw,
      finalStudentProfile: mockProfile,
      sessionToken: loadTestSessionToken,
      isSimulatedLoadTest: true
    });
  }

  let finalStudentProfile: any = null;
  let isNewAttempt = false;
  let attemptAction: 'created' | 'resumed' | 'reattempted' = 'resumed';
  let examWindowExpired = false;

  try {
    // Atomic Database Transaction running on Node.js Server using Client SDK
    await clientRunTransaction(clientDb, async (transaction) => {
      const studentSnap = await transaction.get(studentDocRef);
      const attemptSnap = await transaction.get(attemptDocRef);
      const examSnap = await transaction.get(examDocRef);
      const examDurationMs = examSnap.exists() ? (examSnap.data() as any).duration * 60 * 1000 : null;

      // A. Onboard or fetch Student Profile atomically
      if (studentSnap.exists()) {
        finalStudentProfile = { uid: studentSnap.id, ...studentSnap.data() };
      } else if (matchedStudentData) {
        finalStudentProfile = { uid: resolvedStudentId, ...matchedStudentData };
      } else {
        // Safe auto-onboard fallback
        finalStudentProfile = {
          uid: resolvedStudentId,
          name: username?.trim() || 'Candidate',
          rollNumber: rollNumber.trim(),
          schoolId: finalSchoolId,
          role: 'student',
          permissions: ['take_exams'],
          createdAt: now.toISOString(),
          class: 'Adaptive Cluster'
        };
        transaction.set(studentDocRef, finalStudentProfile);
      }

      // B. Onboard or update Exam Attempt state atomically
      if (attemptSnap.exists()) {
        const attemptData = attemptSnap.data() as any;

        // 'expired' needs the exact same canReattempt gate as 'completed' — a school
        // re-triggering an expired attempt (SchoolStudentOnboarding's handleReTriggerInvite)
        // sets canReattempt:true expecting the student to get back in, same as it does for
        // a completed one. Without 'expired' here, a re-triggered student would hit the
        // resume branch below, immediately re-expire again, and canReattempt would never
        // even be consulted.
        if (attemptData.status === 'completed' || attemptData.status === 'expired') {
          if (attemptData.canReattempt) {
            attemptAction = 'reattempted';
            transaction.update(attemptDocRef, {
              status: 'started',
              score: 0,
              answers: [],
              startTime: now.toISOString(),
              canReattempt: false
            });
          } else if (attemptData.status === 'expired') {
            examWindowExpired = true;
          } else {
            throw new Error('EXAM_ALREADY_COMPLETED');
          }
        } else {
          if (attemptData.deviceFootprint && attemptData.deviceFootprint !== clientFootprint) {
            throw new Error(
              'SESSION_HIJACK_BLOCKED: Mismatched browser/device footprint registered for this unique link. Please complete on your primary device or request a clean reset from terminal administrators.'
            );
          }

          // Lazy expiry: nothing proactively flips an abandoned attempt once its exam
          // window passes, so check it here on the one path a student would come back
          // through — resuming a stale link days later shouldn't silently re-open the exam.
          // Includes any school-granted extraTime (ExamInterface.tsx honors this live during
          // the exam via onSnapshot), or a student who legitimately got extra minutes could
          // be wrongly expired if their session drops and they resume within their real,
          // extended window but past the exam's base duration.
          // Note: this write must land via a normal (non-throwing) transaction return —
          // clientRunTransaction only applies queued transaction.update/set/delete calls
          // AFTER the callback resolves, so throwing here would discard this update too.
          const effectiveDurationMs = examDurationMs !== null ? examDurationMs + (attemptData.extraTime || 0) * 60 * 1000 : null;
          const elapsedMs = now.getTime() - new Date(attemptData.startTime).getTime();
          if (effectiveDurationMs && elapsedMs > effectiveDurationMs) {
            examWindowExpired = true;
            transaction.update(attemptDocRef, { status: 'expired' });
          } else {
            // Active session resume
            transaction.update(attemptDocRef, {
              lastResumedAt: now.toISOString(),
              status: 'started'
            });
          }
        }
      } else {
        // Initial clean session booking
        isNewAttempt = true;
        attemptAction = 'created';
        const newAttemptData = {
          examId: finalExamId,
          examTitle: examTitle || 'Single Term Link Entry Exam',
          studentId: resolvedStudentId,
          studentName: finalStudentProfile.name,
          studentEmail: finalStudentProfile.email || `${rollNumber.trim().toLowerCase()}@school.com`,
          schoolId: finalSchoolId,
          answers: [],
          score: 0,
          startTime: now.toISOString(),
          status: 'started',
          deviceFootprint: clientFootprint || 'GENERIC_BROWSER_PLATFORM',
          ephemeralToken: Buffer.from(Math.random().toString()).toString('base64').substring(0, 16),
          timePerQuestion: {}
        };
        transaction.set(attemptDocRef, newAttemptData);
      }
    });

    if (examWindowExpired) {
      return res.status(410).json({
        code: 'EXAM_WINDOW_EXPIRED',
        error: "This exam's time window has passed. Ask your school to re-trigger a fresh attempt.",
        attemptIdRaw
      });
    }

    // Invite-link students never go through Firebase Auth, so this is the only place that
    // can mint their session — without it, every subsequent /api/db/write during the exam
    // (autosave, proctoring logs, final submit) would 401.
    const sessionToken = signSessionToken({
      uid: resolvedStudentId,
      role: 'student',
      schoolId: finalSchoolId,
      email: finalStudentProfile?.email || `${rollNumber.trim().toLowerCase()}@school.com`
    });

    // Best-effort: mark a per-student invitation link as consumed once it has actually
    // produced a brand-new attempt (not a resume of an existing one).
    if (inviteToken && !inviteIsFallback && isNewAttempt) {
      try {
        await clientUpdateDoc(clientDoc(clientDb, 'invitations', inviteToken), {
          status: 'used',
          consumedAt: now.toISOString()
        });
      } catch (inviteErr) {
        console.warn('Failed to mark invitation as consumed (non-fatal):', inviteErr);
      }
    }

    return res.status(200).json({
      success: true,
      resolvedStudentId,
      attemptIdRaw,
      finalStudentProfile,
      sessionToken,
      isNewAttempt,
      attemptAction
    });
  } catch (transErr: any) {
    const errMsg = transErr?.message || String(transErr);

    // Provide explicit parseable error responses
    if (errMsg.includes('EXAM_ALREADY_COMPLETED')) {
      console.warn('Handled Gatekeeper rule: EXAM_ALREADY_COMPLETED');
      return res.status(409).json({
        code: 'EXAM_ALREADY_COMPLETED',
        error: ' This assessment attempt has already been submitted and completed.',
        attemptIdRaw
      });
    }
    if (errMsg.includes('SESSION_HIJACK_BLOCKED')) {
      console.warn('Handled Gatekeeper rule:', errMsg);
      return res.status(403).json({ code: 'SESSION_HIJACK_BLOCKED', error: errMsg });
    }

    console.error('Transact Error in Node Gatekeeper:', transErr);
    return res.status(500).json({ code: 'TRANSACTION_FAIL', error: errMsg });
  }
});

export default router;
