import crypto from 'crypto';
import { generateEduKey } from '../../shared/idGenerator';
import { clientDb, clientDoc, clientWriteBatch, clientSetDoc, clientUpdateDoc, clientDeleteDoc } from '../firestoreClient';
import { invalidateCache } from './cache';
import { logger } from '../lib/logger';

// In-Memory Write Queue for Cushioning bursty exam submissions and high-frequency proctor logs
export interface WriteTask {
  id: string;
  type: 'add' | 'set' | 'update' | 'delete';
  collectionName: string;
  docId?: string;
  data?: any;
  // When this task entered the queue. Only used to report the oldest pending task's age —
  // the leading indicator of the queue falling behind, which shows up here well before it
  // shows up as request latency or as errors.
  enqueuedAt: number;
  resolve: (value: any) => void;
  reject: (reason: any) => void;
}

const writeQueue: WriteTask[] = [];
let isProcessingQueue = false;

const WRITE_BATCH_SIZE = 500; // Firestore's actual per-batch operation limit
const MAX_CONCURRENT_BATCHES = 12; // bounds how many batch-commit calls run at once per tick

// Drain rate is ~WRITE_BATCH_SIZE * MAX_CONCURRENT_BATCHES per 1.2s tick (~5,000 ops/sec).
// If Firestore itself slows down (quota throttling, an outage, a slow region) faster than
// requests keep arriving, this in-memory array has no other bound and will grow until the
// Cloud Run instance OOMs — taking down every in-flight write for every student on that
// instance, not just the ones that caused the backlog. Capping it turns that into a
// controlled 503 for the newest requests instead, once ~4 ticks of backlog have piled up.
const MAX_QUEUE_SIZE = 20000;

export async function processWriteBatch(batchToProcess: WriteTask[]): Promise<void> {
  try {
    const batch = clientWriteBatch(clientDb);

    for (const task of batchToProcess) {
      if (task.type === 'add' && !task.docId) {
        // Generate an edu-autogenerated unique key using pattern strategy
        task.docId = generateEduKey(task.collectionName);
      }

      const ref = clientDoc(clientDb, task.collectionName, task.docId!);
      if (task.type === 'add' || task.type === 'set') {
        batch.set(ref, task.data || {}, { merge: true });
      } else if (task.type === 'update') {
        batch.update(ref, task.data || {});
      } else if (task.type === 'delete') {
        batch.delete(ref);
      }
    }

    await batch.commit();

    const impactedCollections = new Set<string>();
    for (const task of batchToProcess) {
      impactedCollections.add(task.collectionName);
    }
    impactedCollections.forEach((col) => invalidateCache(col));

    for (const task of batchToProcess) {
      task.resolve({ success: true, id: task.docId });
    }
  } catch (err: any) {
    logger.warn('Batch write failed, falling back to sequential writes', { batchSize: batchToProcess.length, error: err });
    // Fallback to sequential execution so that non-failing individual writes can still succeed
    for (const task of batchToProcess) {
      try {
        if (task.type === 'add' && !task.docId) {
          task.docId = generateEduKey(task.collectionName);
        }
        const ref = clientDoc(clientDb, task.collectionName, task.docId!);
        if (task.type === 'add' || task.type === 'set') {
          await clientSetDoc(ref, task.data || {}, { merge: true });
        } else if (task.type === 'update') {
          await clientUpdateDoc(ref, task.data || {});
        } else if (task.type === 'delete') {
          await clientDeleteDoc(ref);
        }
        invalidateCache(task.collectionName);
        task.resolve({ success: true, id: task.docId });
      } catch (individualErr: any) {
        logger.error('Write task failed', { collectionName: task.collectionName, docId: task.docId, type: task.type, error: individualErr });
        task.reject(individualErr);
      }
    }
  }
}

// Drains the FULL backlog each call — in parallel batches, bounded by MAX_CONCURRENT_BATCHES
// — rather than a single fixed-size batch per tick. A single-batch-per-tick design caps
// throughput at ~333 writes/sec (400 ops / 1.2s); at up to ~100k concurrent students each
// autosaving every ~30s, sustained demand is ~3,300 writes/sec, so a fixed single batch would
// fall permanently behind under real exam-day load and grow an ever-larger in-memory backlog.
//
// Called from two places: the interval below (backstop) and enqueueWrite (eager trigger).
// Under heavy concurrent async load (e.g. many simultaneous enroll transactions competing
// for the event loop), a pure setInterval can get starved — measured under a 1500-concurrent
// real-Firestore load test, the interval fired only 21 times in 3.5 minutes instead of the
// expected ~175, letting writes queue for up to 100+ seconds before a flush got a turn.
// Triggering a flush attempt immediately on enqueue (not just waiting for the timer) gives
// pending writes a chance to run at the next available microtask/await point instead of
// depending solely on a timer callback that can be delayed arbitrarily. isProcessingQueue
// still guards against concurrent runs, so redundant triggers are cheap no-ops.
export async function flushQueue(): Promise<void> {
  if (writeQueue.length === 0 || isProcessingQueue) return;
  isProcessingQueue = true;

  try {
    while (writeQueue.length > 0) {
      const group: WriteTask[][] = [];
      // Captured before the splice below empties the queue, so the reported depth/age
      // describe the backlog this flush actually found.
      const depthBeforeFlush = writeQueue.length;
      const oldestTaskAgeMs = Date.now() - writeQueue[0].enqueuedAt;
      const flushStartedAt = Date.now();

      for (let i = 0; i < MAX_CONCURRENT_BATCHES && writeQueue.length > 0; i++) {
        group.push(writeQueue.splice(0, WRITE_BATCH_SIZE));
      }
      const totalOps = group.reduce((sum, b) => sum + b.length, 0);
      await Promise.all(group.map(processWriteBatch));

      // Structured, so Cloud Logging can turn these into log-based metrics. queueDepth and
      // oldestTaskAgeMs are the two numbers to alert on during an exam window — a sustained
      // rise in either means writes are arriving faster than Firestore is accepting them,
      // and the MAX_QUEUE_SIZE rejection below is where that ends if it isn't caught.
      logger.info('Write queue flush', {
        batches: group.length,
        operations: totalOps,
        queueDepth: depthBeforeFlush,
        queueRemaining: writeQueue.length,
        oldestTaskAgeMs,
        flushDurationMs: Date.now() - flushStartedAt
      });
    }
  } finally {
    isProcessingQueue = false;
  }
}

// Current backlog size. Read by the readiness probe so a saturating queue is visible from
// outside the process, not only in logs.
export function getQueueDepth(): number {
  return writeQueue.length;
}

const flushInterval = setInterval(() => {
  flushQueue().catch((err) => logger.error('Write queue flush error', { error: err }));
}, 1200);

// Nothing should keep the process alive purely to run this timer — on shutdown the drain is
// driven explicitly by flushQueue(), not by waiting for the next tick.
flushInterval.unref();

// Enqueues a write task and returns a promise that resolves when the queue flush cycle
// actually commits it (pure extraction of the inline pattern previously in the
// /api/db/write route handler — same behavior, just callable from a route module).
export function enqueueWrite(params: { type: WriteTask['type']; collectionName: string; docId?: string; data?: any }): Promise<any> {
  return new Promise((resolve, reject) => {
    if (writeQueue.length >= MAX_QUEUE_SIZE) {
      reject(new Error('Write queue is saturated — server is falling behind on database writes. Please retry shortly.'));
      return;
    }
    writeQueue.push({
      id: `task_${crypto.randomBytes(8).toString('hex')}`,
      type: params.type,
      collectionName: params.collectionName,
      docId: params.docId,
      data: params.data,
      enqueuedAt: Date.now(),
      resolve,
      reject
    });
    flushQueue().catch((err) => logger.error('Write queue flush error', { error: err }));
  });
}
