import crypto from 'crypto';
import { EduKeyFactory } from '../../src/lib/idGenerator';
import { clientDb, clientDoc, clientWriteBatch, clientSetDoc, clientUpdateDoc, clientDeleteDoc } from '../firestoreClient';
import { invalidateCache } from './cache';

// In-Memory Write Queue for Cushioning bursty exam submissions and high-frequency proctor logs
export interface WriteTask {
  id: string;
  type: 'add' | 'set' | 'update' | 'delete';
  collectionName: string;
  docId?: string;
  data?: any;
  resolve: (value: any) => void;
  reject: (reason: any) => void;
}

const writeQueue: WriteTask[] = [];
let isProcessingQueue = false;

const WRITE_BATCH_SIZE = 500; // Firestore's actual per-batch operation limit
const MAX_CONCURRENT_BATCHES = 12; // bounds how many batch-commit calls run at once per tick

// Drain rate is ~WRITE_BATCH_SIZE * MAX_CONCURRENT_BATCHES per 1.2s tick (~5,000 ops/sec).
// If Firestore itself slows down (quota throttling, an outage, a slow region) faster than
// requests keep arriving, this in-memory array has no other bound and will grow until the
// Cloud Run instance OOMs — taking down every in-flight write for every student on that
// instance, not just the ones that caused the backlog. Capping it turns that into a
// controlled 503 for the newest requests instead, once ~4 ticks of backlog have piled up.
const MAX_QUEUE_SIZE = 20000;

export async function processWriteBatch(batchToProcess: WriteTask[]): Promise<void> {
  try {
    const batch = clientWriteBatch(clientDb);

    for (const task of batchToProcess) {
      if (task.type === 'add' && !task.docId) {
        // Generate an edu-autogenerated unique key using pattern strategy
        task.docId = EduKeyFactory.getInstance().generateKey(task.collectionName);
      }

      const ref = clientDoc(clientDb, task.collectionName, task.docId!);
      if (task.type === 'add' || task.type === 'set') {
        batch.set(ref, task.data || {}, { merge: true });
      } else if (task.type === 'update') {
        batch.update(ref, task.data || {});
      } else if (task.type === 'delete') {
        batch.delete(ref);
      }
    }

    await batch.commit();

    const impactedCollections = new Set<string>();
    for (const task of batchToProcess) {
      impactedCollections.add(task.collectionName);
    }
    impactedCollections.forEach((col) => invalidateCache(col));

    for (const task of batchToProcess) {
      task.resolve({ success: true, id: task.docId });
    }
  } catch (err: any) {
    console.error('[WRITE CUSHION WARNING] Batch write failed, falling back to sequential writes:', err);
    // Fallback to sequential execution so that non-failing individual writes can still succeed
    for (const task of batchToProcess) {
      try {
        if (task.type === 'add' && !task.docId) {
          task.docId = EduKeyFactory.getInstance().generateKey(task.collectionName);
        }
        const ref = clientDoc(clientDb, task.collectionName, task.docId!);
        if (task.type === 'add' || task.type === 'set') {
          await clientSetDoc(ref, task.data || {}, { merge: true });
        } else if (task.type === 'update') {
          await clientUpdateDoc(ref, task.data || {});
        } else if (task.type === 'delete') {
          await clientDeleteDoc(ref);
        }
        invalidateCache(task.collectionName);
        task.resolve({ success: true, id: task.docId });
      } catch (individualErr: any) {
        console.error(`[WRITE CUSHION ERROR] Task on "${task.collectionName}" failed:`, individualErr);
        task.reject(individualErr);
      }
    }
  }
}

// Drains the FULL backlog each call — in parallel batches, bounded by MAX_CONCURRENT_BATCHES
// — rather than a single fixed-size batch per tick. A single-batch-per-tick design caps
// throughput at ~333 writes/sec (400 ops / 1.2s); at up to ~100k concurrent students each
// autosaving every ~30s, sustained demand is ~3,300 writes/sec, so a fixed single batch would
// fall permanently behind under real exam-day load and grow an ever-larger in-memory backlog.
//
// Called from two places: the interval below (backstop) and enqueueWrite (eager trigger).
// Under heavy concurrent async load (e.g. many simultaneous enroll transactions competing
// for the event loop), a pure setInterval can get starved — measured under a 1500-concurrent
// real-Firestore load test, the interval fired only 21 times in 3.5 minutes instead of the
// expected ~175, letting writes queue for up to 100+ seconds before a flush got a turn.
// Triggering a flush attempt immediately on enqueue (not just waiting for the timer) gives
// pending writes a chance to run at the next available microtask/await point instead of
// depending solely on a timer callback that can be delayed arbitrarily. isProcessingQueue
// still guards against concurrent runs, so redundant triggers are cheap no-ops.
async function flushQueue(): Promise<void> {
  if (writeQueue.length === 0 || isProcessingQueue) return;
  isProcessingQueue = true;

  try {
    while (writeQueue.length > 0) {
      const group: WriteTask[][] = [];
      for (let i = 0; i < MAX_CONCURRENT_BATCHES && writeQueue.length > 0; i++) {
        group.push(writeQueue.splice(0, WRITE_BATCH_SIZE));
      }
      const totalOps = group.reduce((sum, b) => sum + b.length, 0);
      console.log(`[WRITE CUSHION] Processing ${group.length} batch(es), ${totalOps} operations...`);
      await Promise.all(group.map(processWriteBatch));
    }
  } finally {
    isProcessingQueue = false;
  }
}

setInterval(() => {
  flushQueue().catch((err) => console.error('[WRITE CUSHION] Flush error:', err));
}, 1200);

// Enqueues a write task and returns a promise that resolves when the queue flush cycle
// actually commits it (pure extraction of the inline pattern previously in the
// /api/db/write route handler — same behavior, just callable from a route module).
export function enqueueWrite(params: { type: WriteTask['type']; collectionName: string; docId?: string; data?: any }): Promise<any> {
  return new Promise((resolve, reject) => {
    if (writeQueue.length >= MAX_QUEUE_SIZE) {
      reject(new Error('Write queue is saturated — server is falling behind on database writes. Please retry shortly.'));
      return;
    }
    writeQueue.push({
      id: `task_${crypto.randomBytes(8).toString('hex')}`,
      type: params.type,
      collectionName: params.collectionName,
      docId: params.docId,
      data: params.data,
      resolve,
      reject
    });
    flushQueue().catch((err) => console.error('[WRITE CUSHION] Flush error:', err));
  });
}
