import crypto from 'crypto';
import { EduKeyFactory } from '../../src/lib/idGenerator';
import { clientDb, clientDoc, clientWriteBatch, clientSetDoc, clientUpdateDoc, clientDeleteDoc } from '../firestoreClient';
import { invalidateCache } from './cache';

// In-Memory Write Queue for Cushioning bursty exam submissions and high-frequency proctor logs
export interface WriteTask {
  id: string;
  type: 'add' | 'set' | 'update' | 'delete';
  collectionName: string;
  docId?: string;
  data?: any;
  resolve: (value: any) => void;
  reject: (reason: any) => void;
}

const writeQueue: WriteTask[] = [];
let isProcessingQueue = false;

const WRITE_BATCH_SIZE = 500; // Firestore's actual per-batch operation limit
const MAX_CONCURRENT_BATCHES = 12; // bounds how many batch-commit calls run at once per tick

export async function processWriteBatch(batchToProcess: WriteTask[]): Promise<void> {
  try {
    const batch = clientWriteBatch(clientDb);

    for (const task of batchToProcess) {
      if (task.type === 'add' && !task.docId) {
        // Generate an edu-autogenerated unique key using pattern strategy
        task.docId = EduKeyFactory.getInstance().generateKey(task.collectionName);
      }

      const ref = clientDoc(clientDb, task.collectionName, task.docId!);
      if (task.type === 'add' || task.type === 'set') {
        batch.set(ref, task.data || {}, { merge: true });
      } else if (task.type === 'update') {
        batch.update(ref, task.data || {});
      } else if (task.type === 'delete') {
        batch.delete(ref);
      }
    }

    await batch.commit();

    const impactedCollections = new Set<string>();
    for (const task of batchToProcess) {
      impactedCollections.add(task.collectionName);
    }
    impactedCollections.forEach(col => invalidateCache(col));

    for (const task of batchToProcess) {
      task.resolve({ success: true, id: task.docId });
    }
  } catch (err: any) {
    console.error("[WRITE CUSHION WARNING] Batch write failed, falling back to sequential writes:", err);
    // Fallback to sequential execution so that non-failing individual writes can still succeed
    for (const task of batchToProcess) {
      try {
        if (task.type === 'add' && !task.docId) {
          task.docId = EduKeyFactory.getInstance().generateKey(task.collectionName);
        }
        const ref = clientDoc(clientDb, task.collectionName, task.docId!);
        if (task.type === 'add' || task.type === 'set') {
          await clientSetDoc(ref, task.data || {}, { merge: true });
        } else if (task.type === 'update') {
          await clientUpdateDoc(ref, task.data || {});
        } else if (task.type === 'delete') {
          await clientDeleteDoc(ref);
        }
        invalidateCache(task.collectionName);
        task.resolve({ success: true, id: task.docId });
      } catch (individualErr: any) {
        console.error(`[WRITE CUSHION ERROR] Task on "${task.collectionName}" failed:`, individualErr);
        task.reject(individualErr);
      }
    }
  }
}

// Process the cushioned queue every 1.2 seconds to absorb user bursts. Drains the FULL
// backlog each tick — in parallel batches, bounded by MAX_CONCURRENT_BATCHES — rather than
// a single fixed-size batch per tick. A single-batch-per-tick design caps throughput at
// ~333 writes/sec (400 ops / 1.2s); at up to ~100k concurrent students each autosaving
// every ~30s, sustained demand is ~3,300 writes/sec, so a fixed single batch would fall
// permanently behind under real exam-day load and grow an ever-larger in-memory backlog.
setInterval(async () => {
  if (writeQueue.length === 0 || isProcessingQueue) return;
  isProcessingQueue = true;

  try {
    while (writeQueue.length > 0) {
      const group: WriteTask[][] = [];
      for (let i = 0; i < MAX_CONCURRENT_BATCHES && writeQueue.length > 0; i++) {
        group.push(writeQueue.splice(0, WRITE_BATCH_SIZE));
      }
      const totalOps = group.reduce((sum, b) => sum + b.length, 0);
      console.log(`[WRITE CUSHION] Processing ${group.length} batch(es), ${totalOps} operations...`);
      await Promise.all(group.map(processWriteBatch));
    }
  } finally {
    isProcessingQueue = false;
  }
}, 1200);

// Enqueues a write task and returns a promise that resolves when the queue flush cycle
// actually commits it (pure extraction of the inline pattern previously in the
// /api/db/write route handler — same behavior, just callable from a route module).
export function enqueueWrite(params: {
  type: WriteTask['type'];
  collectionName: string;
  docId?: string;
  data?: any;
}): Promise<any> {
  return new Promise((resolve, reject) => {
    writeQueue.push({
      id: `task_${crypto.randomBytes(8).toString('hex')}`,
      type: params.type,
      collectionName: params.collectionName,
      docId: params.docId,
      data: params.data,
      resolve,
      reject
    });
  });
}
